table FishNutrition
	isHidden
	lineageTag: 3328e873-98c0-42e4-960a-2777f28aedde

	column Species
		dataType: string
		isHidden
		lineageTag: f1ffa04c-6e5f-4504-829d-9abfce9da8ae
		summarizeBy: none
		sourceColumn: Species

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Protein_g100g
		dataType: double
		isHidden
		lineageTag: 69a1f069-6d34-4a76-b473-921dbfaf9703
		summarizeBy: sum
		sourceColumn: Protein_g100g

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Omega3_DHAEPA_g100g
		dataType: double
		isHidden
		lineageTag: f81a6347-9e56-4448-b110-0ad68a2d10ad
		summarizeBy: sum
		sourceColumn: Omega3_DHAEPA_g100g

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Zinc_mg100g
		dataType: double
		isHidden
		lineageTag: 06ccdd3e-b170-4c00-a29f-41389c6869e6
		summarizeBy: sum
		sourceColumn: Zinc_mg100g

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Iron_mg100g
		dataType: double
		isHidden
		lineageTag: a8f73930-973c-430d-88a5-57239a2198ea
		summarizeBy: sum
		sourceColumn: Iron_mg100g

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Calcium_mg100g
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6eadcb00-0f7c-4856-a68a-97f89b2f1d3d
		summarizeBy: sum
		sourceColumn: Calcium_mg100g

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column VitaminA_ľg100g
		dataType: int64
		formatString: 0
		lineageTag: d5b0bd27-46f3-4221-8729-99d5a72db3ce
		summarizeBy: sum
		sourceColumn: VitaminA_ľg100g

		annotation SummarizationSetBy = Automatic

	column VitaminD_ľg100g
		dataType: double
		lineageTag: 431c2a34-b2f8-4b94-93c3-8ff6637629d2
		summarizeBy: sum
		sourceColumn: VitaminD_ľg100g

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VitaminB12_ľg100g
		dataType: double
		lineageTag: 89bfc55b-d6cd-40d2-bb92-ae24999f37f0
		summarizeBy: sum
		sourceColumn: VitaminB12_ľg100g

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Selenium_ľg100g
		dataType: int64
		formatString: 0
		lineageTag: d39404d0-343f-4810-8d2c-098b344a44a1
		summarizeBy: sum
		sourceColumn: Selenium_ľg100g

		annotation SummarizationSetBy = Automatic

	column Iodine_ľg100g
		dataType: int64
		formatString: 0
		lineageTag: c3df00e5-ceff-4653-bfd4-1b45db88ed5d
		summarizeBy: sum
		sourceColumn: Iodine_ľg100g

		annotation SummarizationSetBy = Automatic

	partition FishNutrition = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\lisat\Documents\UKSeafood\Data\UKSeafoodSupplyComposition.csv"),[Delimiter=",", Columns=20, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Use First Row as Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Change Type" = Table.TransformColumnTypes(#"Use First Row as Headers",{{"Species", type text}, {"CalendarYear", Int64.Type}, {"SpeciesType", type text}, {"SACN", type text}, {"Imports", type text}, {"Exports", type text}, {"Consumption", type text}, {"Production", type text}, {"Purchases", type text}, {"UKPOP", Int64.Type}, {"Protein_g100g", type number}, {"Omega3_DHAEPA_g100g", type number}, {"VitaminA_ľg100g", type text}, {"VitaminD_ľg100g", type text}, {"VitaminB12_ľg100g", type number}, {"Zinc_mg100g", type number}, {"Iron_mg100g", type number}, {"Calcium_mg100g", Int64.Type}, {"Selenium_ľg100g", Int64.Type}, {"Iodine_ľg100g", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Change Type","NA","",Replacer.ReplaceText,{"Imports"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{{"Imports", Int64.Type}}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Changed Type","NA","",Replacer.ReplaceText,{"Exports"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value1",{{"Exports", Int64.Type}}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Changed Type1","NA","",Replacer.ReplaceText,{"Consumption"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Replaced Value2",{{"Consumption", Int64.Type}}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Changed Type3","NA","",Replacer.ReplaceText,{"Production"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value3",{{"Production", Int64.Type}}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Changed Type2","NA","",Replacer.ReplaceText,{"Purchases"}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Replaced Value4",{{"Purchases", Int64.Type}}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Changed Type4","NA","",Replacer.ReplaceText,{"VitaminA_ľg100g"}),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Replaced Value5",{{"VitaminA_ľg100g", Int64.Type}}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Changed Type5","NA","",Replacer.ReplaceText,{"VitaminD_ľg100g"}),
				    #"Changed Type6" = Table.TransformColumnTypes(#"Replaced Value6",{{"VitaminD_ľg100g", type number}}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Changed Type6","NA","",Replacer.ReplaceText,{"Iodine_ľg100g"}),
				    #"Changed Type7" = Table.TransformColumnTypes(#"Replaced Value7",{{"Iodine_ľg100g", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type7",{"UKPOP"}),
				    #"Grouped Rows" = Table.Group(#"Removed Columns", {"Species", "Protein_g100g", "Omega3_DHAEPA_g100g", "VitaminA_ľg100g", "VitaminD_ľg100g", "VitaminB12_ľg100g", "Zinc_mg100g", "Iron_mg100g", "Calcium_mg100g", "Selenium_ľg100g", "Iodine_ľg100g"}, {{"Count", each Table.RowCount(_), Int64.Type}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Grouped Rows",{"Count"})
				in
				    #"Removed Columns1"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

